### ISSUE TITLE
Support pyserial options in yaml files

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#181]
PySerial supports getting all properties as a dictionary, and replacing some or all properties with a dictionary. I'm proposing that we provide the ability to supply those properties via the yaml file. For example, instead of this (from `conf_files/pocs.yaml`):

```
mount:
    brand: ioptron
    model: 30
    driver: ioptron
    port: /dev/ttyUSB0
    non_sidereal_available: True
```

We'd instead have:
```
mount:
    brand: ioptron
    model: 30
    driver: ioptron
    non_sidereal_available: True
    serial:
       port: /dev/ttyUSB0
       baudrate: 9600
       timeout: 2.0
```

Besides adding the ability to set all of the PySerial properties, this has the added benefit of addressing the pylint complaint that the SerialData constructor takes too many arguments.

**Comment by wtgee** [comment]
Yes, I like this more.

**Comment by jamessynge** [comment]
I note that Observatory.initialize is supposed to be responsible for setting up the communication with devices. I'm thinking we can extend the serial section with info about what to do when the rs232 device is created. For example:
```yaml
mount:
    brand: ioptron
    model: 30
    driver: ioptron
    non_sidereal_available: True
    serial:
       port: /dev/ttyUSB0
       baudrate: 9600
       timeout: 2.0
       validate_port: True   # If true, then the port must exist at create time.
       open_port: False      # If true, then opens port immediately.
```

`open_port: True` implies `validate_port: True` simply because the port must exist in order to be opened. And since Observatory.initialize is supposed to setup communication, I'm proposing that `open_port` be `False` by default, but that `validate_port` be `True` by default.

I propose to create method `rs232.create_serial_data_from_config(serial_config, name)`, where name is something like 'mount' or 'ioptron', determined by the caller. The serial_config param is just the contents of the serial section in the config. This `rs232.create_serial_data_from_config` will be called by `dome.create_dome_from_config`, before creating the Dome instance.

@wtgee Does this make sense to you?
