### ISSUE TITLE
Horizon info read from config

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#416]

**Comment by jermainegug** [comment]
What information are we wanting to put in to the config?

**Comment by wtgee** [comment]
It can go into the config as:
```
location:
    name: Macquarie University Observatory
    latitude: -33.7738 # Degrees
    longitude: 151.1126 # Degrees
    elevation: 100.0 # Meters
    utc_offset: 10.00 # Hours
    horizon: 30 # Degrees
    obstructions:
        - [[40, 30], [40, 75]]
        - [[30, 130], [75, 155], [56, 175]]
    twilight_horizon: -18 # Degrees
    timezone: Australia/Sydney
    gmt_offset: 600
```

Then pull the `horizon` and `obstructions` and build the `Horizon` object as something like `Horizon(obstructions, default_horizon)`
