### ISSUE TITLE
Simulator Camera Creation should not require dummy camera config entries

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#733]
Currently the `create_cameras_from_config` will fail if the `cameras` entry is not populated in the config file. To get a simulator to work one must have at least:

```yaml
cameras:
    auto_detect: False
    devices:
    -
        model: simulator
```

Ideally the simulator should work when no config entries are present.

This manifested itself in AstroHuntsman/huntsman-pocs where the default config file does not contain a `cameras` entry but should be fixed for POCS in general.
