### ISSUE TITLE
Camera.is_primary is wrong

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#95]
I provided a "primary: uid" line in pocs_local.yaml, but the wrong camera is considered primary. pocs_local.yaml:

```
cameras:
    auto_detect: True
    # Arbitrary choice of primary, but now labeled as camera #0,
    # and plugged in to jack #0.
    primary: 6575fc
    devices:
    -
        model: canon_gphoto2
    -
        model: canon_gphoto2
```

And the serial numbers of the cameras start and end as follows:
```
7bab97...cdc74a
6575fc...a6c489
```
